env =  "dev" 
vpc_name =  "dev-ecs-workshop" 
alb_name =  "ecs-workshop-asgard-alb" 
unique_name =  "ecs-workshop" 
cluster_name =  "asgard" 
instance_type =  "t3.micro" 
service_names = [ "odin" ]
service_contexts = [ "/odin" ]
service_health_checks = [ "/odin/actuator/health" ]
service_memories = [ "256" ]
service_cpus = [ "256" ]
docker_images = [ "null" ]