env =  "dev" 
vpc_name =  "dev-ecs-workshop" 
alb_name =  "yogesh-dev-alb" 
unique_name =  "yogesh" 
cluster_name =  "asgard" 
instance_type =  "t3.micro" 
min_instances =  "1" 
max_instances =  "2" 
service_names = [ "odin" ]
service_contexts = [ "/odin" ]
service_health_checks = [ "/odin/actuator/health" ]
service_memories = [ "256" ]
service_cpus = [ "256" ]
docker_images = [ "738035286324.dkr.ecr.us-east-1.amazonaws.com/yogesh/odin:cdd76905e82a46371811215533a4c34aa06864e1" ]
service_min_instances = [ "1" ]
service_max_instances = [ "3" ]